export default [
    {
        // The database created must having these... and can refer to the RoomDetainPage.jsx to see the mockData there also
        id: 1,
        img: "",
        name: "Izrin",
        occupation: "student",
        cleanRoomFrequency: 1,
        address: "No 32, Jalan Bukit Serdang, Taman Bukit Serdang, 43400 Serdang Selangor",
        smoking: false,
        pet: false,
        drink: false,
        isEarly: true,
        distanceFromCollege: 2,
        renterFee: 400,
        matchScore: 98,
    },
    {
        id: 2,
        img: "",
        name: "Ziyang",
        occupation: "Manager",
        cleanRoomFrequency: 3,
        address: "No 32, Jalan Bukit Serdang, Taman Bukit Serdang, 43400 Serdang Selangor",
        smoking: false,
        pet: true,
        drink: false,
        isEarly: true,
        distanceFromCollege: 3,
        renterFee: 1300,
        matchScore: 50,
    },
]